### ISSUE TITLE
Validation Error : Quantity cannot be a fraction

### ISSUE THREAD

**Issue by revant** [mntechnique/lpeb_erpnext#1]
Getting the following error (screenshot attached) when trying to create BOMs.

<img width="1392" alt="screen shot 2017-02-25 at 10 09 35 am" src="https://cloud.githubusercontent.com/assets/1040161/23328954/b1f7af7e-fb53-11e6-80c9-49460e199244.png">

**Comment by revant** [comment]
The UOM for Item in first row is "Nos" and it is set as "must be a whole number", you can change it here /desk#Form/UOM/Nos

**Comment by ishanloya** [comment]
We would like to leave the default setting of having 'Nos' be whole numbers. The error shows up when I enter the Qty as a whole number (4 in the case of the attached image for example)

**Comment by ishanloya** [comment]
If I enter Qty for all items (including those that have default UOM set to Kg) as whole numbers, it creates the BOM

**Comment by vishdha** [comment]
Issue fixed and UOM field made read-only

**Comment by ishanloya** [comment]
Ok. Thanks. Kindly push the changes to our test server.

**Comment by ishanloya** [comment]
The UOM is being pulled automatically now but I'm still seeing the same error with the Qty being a fraction.

![screen shot 2017-02-27 at 9 27 07 am](https://cloud.githubusercontent.com/assets/17540310/23348327/f6ffb2ca-fcce-11e6-95d5-127c6b3894a9.png)

**Comment by vishdha** [comment]
check again

**Comment by ishanloya** [comment]
Ok. Works now. Thanks
