### ISSUE TITLE
Multi-level BOM not created

### ISSUE THREAD

**Issue by ishanloya** [mntechnique/lpeb_erpnext#4]
![screen shot 2017-02-27 at 10 03 26 am](https://cloud.githubusercontent.com/assets/17540310/23348870/1fd55b46-fcd4-11e6-9d63-2d4bdac1ebd0.png)

Referring to the above image, if I create BOMs, system does not create a BOM for SSC with the specified qty of RF1-2. Only BOM for RF1-2 is created. If I try to create BOM for SSC through a new BOQ, that doesn't work either (no error/success message is shown).

**Comment by vishdha** [comment]
You need to Put SSC in Item field. The first Item is root Item that's why its parent Item field should be blank. 

![1](https://cloud.githubusercontent.com/assets/6947417/23354505/8912eb46-fcf7-11e6-8986-b4a95fcd6c65.png)

**Comment by ishanloya** [comment]
Ok. If I use the following BOQ, where SSC is the root item (Qty 1) & RF1-1 is a sub-assembly (Qty 4), when I create BOMs, a multi-level BOM is not created. When I view the BOM for SSC in the BOM tree I cannot expand and see the child items of RF1-1 for example. Since we are doing BOM project-wise, can this multi-level BOM be generated automatically from the BOQ?


<img width="934" alt="screen shot 2017-02-27 at 2 41 55 pm" src="https://cloud.githubusercontent.com/assets/17540310/23355254/ee184786-fcfa-11e6-91c8-639a70533fc8.png">

**Comment by revant** [comment]
The default BOM Tree View supports limited level nesting for selected BOM.
We will create LPEB BOM page to achieve this.

**Comment by ishanloya** [comment]
Ok. When can we try it out?

**Comment by gaurav-naik** [comment]
By default, BOM hierarchy can be set only after submitting child BOMs.

Setting BOM No for item C1:
![bom no c1](https://cloud.githubusercontent.com/assets/17795124/23496128/7e1ee1c0-ff42-11e6-8024-54318a10b73e.png)

On Save:
![bom c1 after](https://cloud.githubusercontent.com/assets/17795124/23496152/9eb63b9a-ff42-11e6-9c47-51745300cf8a.png)

In case the hierarchy needs to be seen before submitting BOMs, it can be displayed on the LPEB BOM page as mentioned in the previous post.
